### ISSUE TITLE
65K methods limit is hit

### ISSUE THREAD

**Issue by abiemann** [amotzte/android-mock-location-for-development#3]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536

for implementation, see : 
https://stackoverflow.com/questions/26515378/dexindexoverflowexception-issue-after-updating-to-latest-appcompat-and-support-l

**Comment by amotzte** [comment]
Would you be interested to to push a PR?

**Comment by abiemann** [comment]
Did it :-)
https://github.com/amotzte/android-mock-location-for-development/pull/4
